project:
  type: book
  output-dir: docs

book:
  title: "The Metacheck Manual"
  subtitle: "Automated Checks of Research Outputs for Best Practices"
  author: "Daniel Lakens"
  date: today
  description: >
    A guide to Metacheck, an R package providing a module based tool
    for checking scientific manuscripts and data repositories for best practices using 
    text search, R code, and optional LLM queries.
  site-url: https://scienceverse.github.io/metacheck_book/
  repo-url: https://github.com/scienceverse/metacheck_book
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    logo: https://scienceverse.github.io/metacheck/logo.png
    style: docked
    collapse-level: 1
  page-footer:
    left: "Built with [Quarto](https://quarto.org)."
    right: "[Metacheck package](https://scienceverse.github.io/metacheck/)"
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - chapters/intro.Rmd
        - chapters/get-started.Rmd
        - chapters/reading-a-paper.Rmd
        - chapters/text-search.Rmd
        - chapters/llms.Rmd
    - part: "Modules"
      chapters:
        - chapters/mod-power.Rmd
        - chapters/mod-prereg-check.Rmd
        - chapters/mod-marginal.Rmd
        - chapters/mod-stat-check.Rmd
        - chapters/mod-stat-p-exact.Rmd
        - chapters/mod-stat-p-nonsig.Rmd
        - chapters/mod-repo-check.Rmd
        - chapters/mod-code-check.Rmd
        - chapters/mod-ref-pubpeer.Rmd
        - chapters/mod-ref-retraction.Rmd
        - chapters/mod-ref-replication.Rmd
    - part: "Working with Papers"
      chapters:
        - chapters/batch.Rmd
        - chapters/local-files.Rmd
        - chapters/papers-databases.Rmd
        - chapters/stats.Rmd
        - chapters/jars.Rmd
    - part: "Advanced Functions"
      chapters:
        - chapters/creating-modules.Rmd
        - chapters/github.Rmd
        - chapters/aspredicted.Rmd
        - chapters/osf-schemas.Rmd
        - chapters/ollama.Rmd
    - part: "Drafts & Work in Progress"
      chapters:
        - drafts/index.qmd
        - drafts/metascience.Rmd
        - drafts/workshop-4m.qmd
        - drafts/grobid-checks.qmd
        - drafts/paper-structure.qmd
        - drafts/check-correct-citations.qmd
        - drafts/validation-p-values.qmd
        - drafts/validation-aspredicted.qmd
        - drafts/validation-effect-size.qmd
        - drafts/validation-osf.qmd

  appendices:
    - chapters/function-reference.Rmd

bibliography: include/book.bib
csl: include/apa.csl

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    code-link: true
    code-copy: true
    toc: true

execute:
  freeze: true
  warning: false
  message: false
