---
title: P Value Module sValidation
format:
  html:
    toc: true
    embed-resources: true
---

```{r}
#| message: false

# library(metacheck)
library(tidyverse)

# use local dev version
library(metacheck)
```

## all_p_values

This module just needs a logical check that it's matching what we'd hope and not what we don't.

```{r}
operators <- c("=", "<", ">", "~",  
               "\u2248", # ~~
               "\u2260", # !=
               "\u2264", # <=
               "\u2265", # >=
               "\u226A", # <<
               "\u226B" # >>
               ) |> paste(collapse = "")

pattern <- paste0(
  "\\bp-?(value)?\\s*", # ways to write p
  "[", operators, "]{1,2}\\s*", # 1-2 operators
  "(n\\.?s\\.?|\\d?\\.\\d+)",# ns or valid numbers
  "\\s*(e\\s*-\\d+)?", # also match scientific notation
  "(\\s*[x\\*]\\s*10\\s*\\^\\s*-\\d+)?" 
)

expected <- c(
  "p=.05",
  "p\n=\n.05",
  "p = .05",
  "p < .05",
  "p > .05",
  "p <= .05",
  "p >= .05",
  "p == .05",
  "p << .05",
  "p >> .05",
  "p ≤ .05",
  "p ≥ .05",
  "p ≪ .05",
  "p ≫ .05",
  "p ≠ .05",
  "p-value = .02",
  "pvalue = .023",
  "p = 0.05",
  "p = 0.05229381290",
  "p = 1.2e-5",
  "p = n.s.",
  "p = ns",
  "p = 1.23x10^-3",
  "p = 1.23 x 10^-3",
  "p = 1.23 x 10 ^ -3",
  "p = 1.23 * 10 ^ -3",
  "p = 1.23e-4",
  "p = 1.23 e-4",
  "p = 1.23 e -4"
)
not <- c(
  "up = 0.23",
  "p = stuff",
  "p = -0.5",
  "p less than 0.05",
  "p = 12.87"
)

table <- data.frame(
  text = c(expected, not),
  expected = rep(c(T, F), c(length(expected), length(not)))
)

table$observed <- grepl(pattern, table$text, "perl" = TRUE)

# filter to mismatches
table[table$expected != table$observed, ]
```

```{r}
table$id <- 1:nrow(table)
m <- module_run(table, "all_p_values")
wrong <- m$table$text != table$text[table$expected]
table[which(wrong), ]
```

```{r}
m$table[, c("text", "p_comp", "p_value")]
```



```{r}
all_p <- module_run(psychsci, "all_p_values")

ptable <- all_p$table |> 
  separate(text, c("p", "operator", "value"), sep = "\\s+", remove = FALSE, fill = "right") |>
  mutate(nval = as.numeric(value))

count(ptable, p, operator)
```

All instances of uppercase P are not p-values.

```{r}
all_p$table |>
  filter(grepl("P", text)) |>
  text_expand(psychsci) |>
  pull(expanded) |>
  unique()
```

## stat_p_exact

Run code from module to get full table

```{r}
p <- all_p$table

  operators <- c("=", "<", ">", "~",
                 "\u2248", # ~~
                 "\u2260", # !=
                 "\u2264", # <=
                 "\u2265", # >=
                 "\u226A", # <<
                 "\u226B" # >>
  ) |> paste(collapse = "")

  # get operator
  pattern <- paste0("[", operators, "]{1,2}")
  matches <- gregexpr(pattern, p$text, perl = TRUE)
  p$p_comp <- regmatches(p$text, matches) |> sapply(`[[`, 1)

  # get value
  pattern <- paste0("(?<=[", operators, "]{1,2}).*$")
  matches <- gregexpr(pattern, p$text, perl = TRUE)
  p$p_value <- regmatches(p$text, matches) |> trimws()
  p$p_value <- suppressWarnings(as.numeric(p$p_value))

  p$imprecise <- p$p_comp == "<" & p$p_value > .001
  p$imprecise <- p$imprecise | !p$p_comp %in% c("=", "<")
  p$imprecise <- p$imprecise | is.na(p$p_value)
```

```{r}
ggplot(p, aes(x = p_value, color = p_comp)) +
  geom_density(linewidth = 1) +
  coord_cartesian(xlim = c(0, 1)) +
  guides(color = guide_legend(position = "inside")) +
  labs(x = "p-value", y = NULL, color = NULL,
       title = "P-Value Distribution by Operator") +
  scale_color_manual(values = c("firebrick", "darkgreen", "dodgerblue3", "darkorchid")) +
  theme_bw(base_size = 13) +
  theme(legend.position.inside = c(.2, .7),
        legend.background = element_blank())

ggsave("~/Desktop/pval.png", width = 7, height= 5)
```


## text

An issue was filed about text ways of stating a p-value, like "the p-value was 0.03". However, all ways to catch that produce way more fale positives for threshold sentences.

https://github.com/scienceverse/metacheck/issues/24

```{r}
pattern <- "\\b\\w+\\s+p(-| )?values?\\s+.{1,20}\\s+[0-9\\.]+"
ptext <- text_search(psychsci, pattern, return = "match")
  

dplyr::count(ptext, text, sort = TRUE)
```

